server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sapatointeligente?useSSL=false
    username: root
    password: guga8802 #qB_*0204
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true